### ISSUE TITLE
Support for .mov files

### ISSUE THREAD

**Issue by shashank2104** [dwyfl/gifplayer#1]
Hi,

Thank you for the awesome library. It's very helpful. 

Is it possible to enhance the library to support .mov/.mp4 files as well?

**Comment by dwyfl** [comment]
Thanks for your interest, but I will most likely not add support for video decoding to this library. Using Google it should not be hard to find JS libraries for h264/mpeg decoding though, if that is what you're looking for.

I've thought about adding video support to [Play the GIF](http://playthegif.slengteng.org/), to keep up with how imgur/giphy/etc are moving towards using real video. But that would simply be a UI to control the video element, and not actual decoding.
